### ISSUE TITLE
Manually setting screen to black and dimmed when no screen saver is set by pressing screensaver button.

### ISSUE THREAD

**Issue by rafuz** [thanksmister/androidthings-mqtt-alarm-panel#14]
Screen timeout seems not to work on the latest release.
All other screensaver fetures work correctly but not the blank/timeout.
Event if I press the sleep icon the screen stays on.

**Comment by thanksmister** [comment]
You have to set a clock or image screensaver of you want to use one. If you don’t use one then screen timeout is up to your device settings. If you had a screen saver and then disabled it, try restarting the app.

**Comment by rafuz** [comment]
If I set a clock or image screensaver it works correctly. I just want to turn off the screen after a definite time and it just does not blank the screen.

**Comment by thanksmister** [comment]
Does your Android device have a screen saver set or a screen timeoit set?  Your device will put itself to sleep without the app have a screen saver set.

**Comment by thanksmister** [comment]
I just realized your on Android Things.  So there is no way to turn off the screen on Android Things, all you can do is dim it. I suggest you use the clock and set the screen brightness low. It dims the screen when there is a screen saver running.  But there is no black screen, I guess that’s what you expected.

**Comment by thanksmister** [comment]
I guess a feature request would be to turn the screen black and do maximum dim if there are no screensavers set and you manually hit the "Zzz" button to turn on the screen saver.   Optionally, I would have to add a "Use blank screensaver" option because there is a use case for not using any screensaver.

**Comment by rafuz** [comment]
Ok this is what really what I am asking for. The previous version worked exactly this way, if a screensaver was not set it simply turned down the screen after sleep time.

**Comment by thanksmister** [comment]
The option to manage screen dimming was removed in Android Things 1.0 because they said screen dimming across devices wasn't reliable.   They removed access to the ScreenManager so now we rely on the  WindowManager.LayoutParams to dim the screen.   Before it was automatically done using the ScreenManager, hence a new feature needs to be added.
