### ISSUE TITLE
Image does not boot

### ISSUE THREAD

**Issue by rhannink** [thanksmister/androidthings-mqtt-alarm-panel#16]
Hello,

I tried writing the img file to an 8 Gb SD card. But is doesn't boot in the Raspberry Pi. I tried to flash it from MacOS and from Windows, tried different cards and different versions the  images, but it just won't boot on my Raspberry Pi 3B

With kind regards,

Remco Hannink

**Comment by rhannink** [comment]
Hello,

Did some additional testing and searching and I found out that the Raspberry Pi 3 B+ is not yet supported. You need a Raspberry Pi 3 B, which is not manufactured anymore..........

**Comment by thanksmister** [comment]
Unfortunately its up to Google to offer support for the Raspberry Pi 3 B+.  I have my doubts they will since they are targeting Android Things to higher priced and closed boards.   Raspberry Pi is for development only at this time and not for production due to "security issues" with the SD card being able to be removed.
