### ISSUE TITLE
Timeout for Notifications and Setup Screen

### ISSUE THREAD

**Issue by e2m32** [thanksmister/androidthings-mqtt-alarm-panel#3]
Hi! Love the app. I am experiencing 2 issues related to what I believe is some kind of timeout. I haven't seen this anywhere and am wondering if this is just related to my device.

I am running the app on an old Galaxy S3, android v4.4 kitkat.

1. When in the settings I could be entering data and the screen will timeout and return back to the main screen for the alarm panel.

2. When receiving a MQTT message from 'home/notification', the message does appear, but it times out so fast that if you blink you will miss it. It times out so fast you can't even see what the message was.

Is this just me?

**Comment by thanksmister** [comment]
No I don't think it's just you. What do you have set for your pending times
in the application?

**Comment by thanksmister** [comment]
Looks like you have the screen timeout in the setting screen set really
low.  This turns on the screen saver which boots you out of the settings
screen and clears the dialogs.    I will change the behavior in the next
release, but for now, change the "Screen timeout after.." time to something
higher.  The minimum is 15 seconds, so move fast.  If not then you have
have uninstall and install the application again to reset everything.

Originally the timeout on the settings screen was in place so users didn't leave their alarm system in the settings view, which would not activate the alarm.  Because you can go to the settings from the alarm view if armed or in away mode.

**Comment by thanksmister** [comment]
Sorry, you are not using Android Things, you said you were on a Galaxy
device.  I guess you are using the Android Things Github to report the
issue.  This should be in the Android device version instead.

**Comment by e2m32** [comment]
Hi Michael,

Sorry, I didn't realize there was another github for the Android device
version. I didn't see the screen timeout setting in the Settings. I will
look again.

I have the Pending time in the app set to default, but the Alarm is set to
2 seconds right now while I am testing/setting everything up. Could this be
an issue with them not synced up?

Thanks Mister!

I

**Comment by thanksmister** [comment]
It's a screen timeout issue. Check under the screen saver settings for that
setting. I think you have it really low. I will change the settings screen
to use it's own timeout rather than use the screen saver.
